### ISSUE TITLE
chore: Update links to solutions on the project readme

### ISSUE THREAD

**Issue by orama254** [codemuse-ke/ace-technical-interview-js-py#45]
The current links on the readme aren't resolving to the desired solutions page, returning a 404 page not found.

**SOLUTION:**
Update the current links to reflect the new project structure.

<br />
Let me know if this is something you would want assistance with.

**Comment by codemuse-ke** [comment]
Thank you for bringing that to my attention. I made a few changes that may have caused the issue. Some references may not be available because this is an ongoing project. If you would like to contribute to some topics, please feel free to open a pull request for the same

**Comment by orama254** [comment]
Welcome, most of the links have been resolved, I'll close this as resolved

Cheers.
